#!/usr/bin/python3

# Copyright © 2012, 2014 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import re
import subprocess as ipc

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('device')
    parser.add_argument('begin', type=int)
    parser.add_argument('end', type=int)
    options = parser.parse_args()
    return do(options)

def debugfs(device, *command):
    commandline = ['debugfs', '-R', ' '.join(map(str, command)), device]
    child = ipc.Popen(commandline, stderr=ipc.PIPE, stdout=ipc.PIPE)
    stdout, stderr = child.communicate()
    if child.returncode != 0:
        raise IOError
    return [line.decode('ASCII') for line in stdout.splitlines()]

def do(options):
    if options.end < options.begin:
        raise ValueError
    testb = debugfs(options.device, 'testb', options.begin, options.end - options.begin + 1)
    inodes = set()
    blocks = set()
    for line in testb:
        match = re.match('^Block (\d+) marked in use$', line)
        if match is not None:
            blocks.add(int(match.group(1)))
    del testb
    while blocks:
        block = blocks.pop()
        header, icheck = debugfs(options.device, 'icheck', block)
        assert header == 'Block\tInode number'
        block_s, inode = icheck.split('\t')
        assert block == int(block_s)
        if inode == '<block not found>':
            print('<block {0} not found>'.format(block))
            continue
        else:
            inode = int(inode)
        if inode in inodes:
            continue
        else:
            inodes.add(inode)
        ncheck = debugfs(options.device, 'ncheck', inode)
        header = ncheck[0]
        assert header == 'Inode\tPathname'
        if len(ncheck) == 1:
            print('<inode {0} not found>'.format(inode))
            continue
        else:
            [ncheck] = ncheck[1:]
        inode2, path = ncheck.split('\t', 1)
        print(path)
        stat = debugfs(options.device, 'stat', '<{0}>'.format(inode))
        try:
            i = stat.index('BLOCKS:')
        except LookupError:
            i = stat.index('EXTENTS:')
        block_stat = stat[i + 1]
        for match in re.finditer(': ?([0-9]+)(?:-([0-9]+))?', block_stat):
            l, r = match.groups()
            l = int(l)
            if r is None:
                r = l
            else:
                r = int(r)
            for i in range(l, r + 1):
                blocks.discard(i)

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
